name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 19 * * *'    

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  tests-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: Run tests
      run: dotnet test -l:html
      working-directory: .

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ./TestResults/*.html
          
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./Tests/TestResults/
        
    - name: Download Test Artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./Tests/TestResults/
