name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 19 * * *'    

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: .

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: Create test results directory
      run: mkdir -p Tests/TestResults
      working-directory: .  

    - name: Run tests
      run: dotnet test Tests/Tests.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results/test-results.trx"
      working-directory: .

    - name: Convert TRX File to HTML
      run: |
        dotnet tool install -g trx2html
        trx2html test-results/test-results.trx -o test-results/test-results.html

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
          
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/ 
        
    - name: Download Test Artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./downloaded-test-results/    